groups:
  - name: system-alerts
    rules:
    - alert: ServiceDown
      expr: up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: 'Service {{ $labels.service }} is down'
        description: 'Service {{ $labels.instance }} is unavailable. Go here: {{ $labels.service }}'
    - alert: AlwaysFiring
      expr: vector(1)
      annotations:
        summary: 'Always up'
        description: "Something went truly wrong"
    - alert: BusinessProcessFailure
      expr: random_business_metric == 0
      for: 5m
      labels:
        service: "Critical business thing"
        severity: critical
      annotations:
        description: Process {{ $labels.service }} has failed!