server:
  port: 10101

log-mappings:
  applications: [ ]
  defaultMapping:
    warningKeywords: [ "WARNING", "WARN" ]
    errorKeywords: [ "ERROR" ]

logs-storage:
  file:
    enabled: true
    path: "/tmp/logs"
  elasticsearch:
    enabled: true
    path: "http://localhost:9200"

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]